# Generated by Django 3.0.6 on 2020-05-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0005_remove_device_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=32, verbose_name='标签识别码')),
                ('name', models.CharField(max_length=32, verbose_name='标签名称')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device', unique=True, verbose_name='关联基站')),
            ],
        ),
    ]
