# Generated by Django 3.0.6 on 2020-05-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0005_remove_device_is_online'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device.Device',
                                       verbose_name='关联基站'),
        ),
    ]
