# Generated by Django 3.0.6 on 2020-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0005_auto_20200511_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tid',
            field=models.CharField(max_length=32, unique=True, verbose_name='标签识别码'),
        ),
    ]
