# Generated by Django 3.0.6 on 2020-05-13 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tag', '0006_auto_20200511_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='触发器名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('callback_url', models.TextField(verbose_name='回调URL')),
                ('callback_protocol', models.CharField(max_length=16, verbose_name='回调协议')),
                ('callback_params', models.TextField(verbose_name='回调参数')),
                ('callback_headers', models.TextField(verbose_name='回调附加HTTP Header')),
                ('callback_method',
                 models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT')], verbose_name='请求类型')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                'scope', models.IntegerField(choices=[(1, '全局（对某个用户而言）'), (2, '基站'), (3, 'TAG')], verbose_name='作用范围')),
                ('target', models.IntegerField(verbose_name='作用目标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.IntegerField(verbose_name='作用顺序')),
                ('trigger',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Trigger', verbose_name='触发器')),
            ],
        ),
    ]
