# Generated by Django 3.0.6 on 2020-05-13 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0007_callback_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
