# Generated by Django 3.0.6 on 2020-07-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200706_1424'),
        ('tag', '0011_auto_20200706_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.Device', verbose_name='关联基站'),
            preserve_default=False,
        ),
    ]
