# Generated by Django 3.0.6 on 2020-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0012_tagcategory_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='color',
            field=models.CharField(default='#000000', max_length=32, verbose_name='颜色'),
            preserve_default=False,
        ),
    ]
