# Generated by Django 3.0.6 on 2020-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0015_auto_20200707_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcategory',
            name='light_detect_on',
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='move_detect_on',
        ),
        migrations.AddField(
            model_name='tag',
            name='light_detect_on',
            field=models.BooleanField(default=True, verbose_name='启用光线传感器'),
        ),
        migrations.AddField(
            model_name='tag',
            name='move_detect_on',
            field=models.BooleanField(default=False, verbose_name='启用运动传感器'),
        ),
    ]
