# Generated by Django 3.0.6 on 2020-07-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0016_auto_20200707_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='name',
            field=models.CharField(default=2, max_length=64, unique=True, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
