# Generated by Django 3.0.6 on 2020-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0021_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='mute_mode_on',
            field=models.BooleanField(default=False, verbose_name='静音模式'),
        ),
    ]
