# Generated by Django 3.0.6 on 2020-07-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0022_tag_mute_mode_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
    ]
