# Generated by Django 3.0.6 on 2020-05-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True, verbose_name='识别码')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='设备名')),
                ('is_online', models.BooleanField(verbose_name='是否在线')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('belongs_to',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='属于用户')),
            ],
        ),
    ]
