# Generated by Django 3.0.6 on 2020-05-10 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name', '-uid')},
        ),
        migrations.AddField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='新建时间'),
            preserve_default=False,
        ),
    ]
