# Generated by Django 3.0.6 on 2020-05-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(max_length=16, unique=True, verbose_name='识别码'),
        ),
    ]
