# Generated by Django 3.0.6 on 2020-05-11 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0004_auto_20200511_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_online',
        ),
    ]
