# Generated by Django 3.0.6 on 2020-07-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200706_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(default='5efb5427be7a7d02caca41a6_IK_0001', max_length=64, verbose_name='华为云设备ID'),
            preserve_default=False,
        ),
    ]
