# Generated by Django 3.0.6 on 2020-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=128, verbose_name='华为云设备ID'),
        ),
    ]
