# Generated by Django 3.0.6 on 2020-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_auto_20200707_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='map_picture_h',
            field=models.PositiveIntegerField(default=0, verbose_name='地图高度'),
        ),
        migrations.AlterField(
            model_name='device',
            name='map_picture_w',
            field=models.PositiveIntegerField(default=0, verbose_name='地图宽度'),
        ),
    ]
