# Generated by Django 3.0.6 on 2020-07-07 15:49

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20200707_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='map_picture_path',
            field=models.ImageField(default=None, height_field='map_picture_h', null=True, upload_to=device.models.get_image_upload_path, verbose_name='地图', width_field='map_picture_w'),
        ),
    ]
