# Generated by Django 3.0.6 on 2020-07-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_auto_20200707_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='map_picture_path',
            new_name='map_picture',
        ),
    ]
